"""add risk_reasons to login_attempts

Revision ID: ac99040b77e3
Revises: 9a01_add_mfa_otp_fields
Create Date: 2025-12-16 13:44:05.767171

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa

def upgrade():
    op.add_column(
        "login_attempts",
        sa.Column("risk_reasons", sa.Text(), nullable=True)
    )

def downgrade():
    op.drop_column("login_attempts", "risk_reasons")


# revision identifiers, used by Alembic.
revision = 'ac99040b77e3'
down_revision = '9a01_add_mfa_otp_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_ip')
        batch_op.drop_column('last_device_info')
        batch_op.drop_column('require_mfa')
        batch_op.drop_column('mfa_expires_at')
        batch_op.drop_column('mfa_code_hash')
        batch_op.drop_column('mfa_pending')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_pending', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mfa_code_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mfa_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('require_mfa', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
